country_currency_data = {
    "United Arab Emirates": "AED",
    "Afghanistan": "AFN",
    "Albania": "ALL",
    "Armenia": "AMD",
    "Netherlands Antilles": "ANG",
    "Angola": "AOA",
    "Argentina": "ARS",
    "Australia": "AUD",
    "Aruba": "AWG",
    "Azerbaijan": "AZN",
    "Bosnia and Herzegovina": "BAM",
    "Barbados": "BBD",
    "Bangladesh": "BDT",
    "Bulgaria": "BGN",
    "Bahrain": "BHD",
    "Burundi": "BIF",
    "Bermuda": "BMD",
    "Brunei": "BND",
    "Bolivia": "BOB",
    "Brazil": "BRL",
    "Bahamas": "BSD",
    "Bhutan": "BTN",
    "Botswana": "BWP",
    "Belarus": "BYN",
    "Belize": "BZD",
    "Canada": "CAD",
    "Democratic Republic of the Congo": "CDF",
    "Switzerland": "CHF",
    "Chile": "CLP",
    "China": "CNY",
    "Colombia": "COP",
    "Costa Rica": "CRC",
    "Cuba": "CUP",
    "Cape Verde": "CVE",
    "Czech Republic": "CZK",
    "Djibouti": "DJF",
    "Denmark": "DKK",
    "Dominican Republic": "DOP",
    "Algeria": "DZD",
    "Egypt": "EGP",
    "Eritrea": "ERN",
    "Ethiopia": "ETB",
    "European Union": "EUR",
    "Fiji": "FJD",
    "Falkland Islands": "FKP",
    "Faroe Islands": "FOK",
    "United Kingdom": "GBP",
    "Georgia": "GEL",
    "Guernsey": "GGP",
    "Ghana": "GHS",
    "Gibraltar": "GIP",
    "The Gambia": "GMD",
    "Guinea": "GNF",
    "Guatemala": "GTQ",
    "Guyana": "GYD",
    "Hong Kong": "HKD",
    "Honduras": "HNL",
    "Croatia": "HRK",
    "Haiti": "HTG",
    "Hungary": "HUF",
    "Indonesia": "IDR",
    "Israel": "ILS",
    "Isle of Man": "IMP",
    "India": "INR",
    "Iraq": "IQD",
    "Iran": "IRR",
    "Iceland": "ISK",
    "Jersey": "JEP",
    "Jamaica": "JMD",
    "Jordan": "JOD",
    "Japan": "JPY",
    "Kenya": "KES",
    "Kyrgyzstan": "KGS",
    "Cambodia": "KHR",
    "Kiribati": "KID",
    "Comoros": "KMF",
    "South Korea": "KRW",
    "Kuwait": "KWD",
    "Cayman Islands": "KYD",
    "Kazakhstan": "KZT",
    "Laos": "LAK",
    "Lebanon": "LBP",
    "Sri Lanka": "LKR",
    "Liberia": "LRD",
    "Lesotho": "LSL",
    "Libya": "LYD",
    "Morocco": "MAD",
    "Moldova": "MDL",
    "Madagascar": "MGA",
    "North Macedonia": "MKD",
    "Myanmar": "MMK",
    "Mongolia": "MNT",
    "Macau": "MOP",
    "Mauritania": "MRU",
    "Mauritius": "MUR",
    "Maldives": "MVR",
    "Malawi": "MWK",
    "Mexico": "MXN",
    "Malaysia": "MYR",
    "Mozambique": "MZN",
    "Namibia": "NAD",
    "Nigeria": "NGN",
    "Nicaragua": "NIO",
    "Norway": "NOK",
    "Nepal": "NPR",
    "New Zealand": "NZD",
    "Oman": "OMR",
    "Panama": "PAB",
    "Peru": "PEN",
    "Papua New Guinea": "PGK",
    "Philippines": "PHP",
    "Pakistan": "PKR",
    "Poland": "PLN",
    "Paraguay": "PYG",
    "Qatar": "QAR",
    "Romania": "RON",
    "Serbia": "RSD",
    "Russia": "RUB",
    "Rwanda": "RWF",
    "Saudi Arabia": "SAR",
    "Solomon Islands": "SBD",
    "Seychelles": "SCR",
    "Sudan": "SDG",
    "Sweden": "SEK",
    "Singapore": "SGD",
    "Saint Helena": "SHP",
    "Sierra Leone": "SLE",
    "Somalia": "SOS",
    "Suriname": "SRD",
    "South Sudan": "SSP",
    "São Tomé and Príncipe": "STN",
    "Syria": "SYP",
    "Eswatini": "SZL",
    "Thailand": "THB",
    "Tajikistan": "TJS",
    "Turkmenistan": "TMT",
    "Tunisia": "TND",
    "Tonga": "TOP",
    "Turkey": "TRY",
    "Trinidad and Tobago": "TTD",
    "Tuvalu": "TVD",
    "Taiwan": "TWD",
    "Tanzania": "TZS",
    "Ukraine": "UAH",
    "Uganda": "UGX",
    "United States": "USD",
    "Uruguay": "UYU",
    "Uzbekistan": "UZS",
    "Venezuela": "VES",
    "Vietnam": "VND",
    "Vanuatu": "VUV",
    "Samoa": "WST",
    "Central African CFA Franc": "XAF",
    "Organisation of Eastern Caribbean States": "XCD",
    "International Monetary Fund": "XDR",
    "West African CFA franc": "XOF",
    "Collectivités d'Outre-Mer": "XPF",
    "Yemen": "YER",
    "South Africa": "ZAR",
    "Zambia": "ZMW",
    "Zimbabwe": "ZWL"
}
api_key = "c67aaf16e1b3fc94eda*****"
url = "https://v6.exchangerate-api.com/v6/c67aaf16e1b3fc94eda*****/latest/{country}"
country_names = [
    "United Arab Emirates",
    "Afghanistan",
    "Albania",
    "Armenia",
    "Netherlands Antilles",
    "Angola",
    "Argentina",
    "Australia",
    "Aruba",
    "Azerbaijan",
    "Bosnia and Herzegovina",
    "Barbados",
    "Bangladesh",
    "Bulgaria",
    "Bahrain",
    "Burundi",
    "Bermuda",
    "Brunei",
    "Bolivia",
    "Brazil",
    "Bahamas",
    "Bhutan",
    "Botswana",
    "Belarus",
    "Belize",
    "Canada",
    "Democratic Republic of the Congo",
    "Switzerland",
    "Chile",
    "China",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Cape Verde",
    "Czech Republic",
    "Djibouti",
    "Denmark",
    "Dominican Republic",
    "Algeria",
    "Egypt",
    "Eritrea",
    "Ethiopia",
    "European Union",
    "Fiji",
    "Falkland Islands",
    "Faroe Islands",
    "United Kingdom",
    "Georgia",
    "Guernsey",
    "Ghana",
    "Gibraltar",
    "The Gambia",
    "Guinea",
    "Guatemala",
    "Guyana",
    "Hong Kong",
    "Honduras",
    "Croatia",
    "Haiti",
    "Hungary",
    "Indonesia",
    "Israel",
    "Isle of Man",
    "India",
    "Iraq",
    "Iran",
    "Iceland",
    "Jersey",
    "Jamaica",
    "Jordan",
    "Japan",
    "Kenya",
    "Kyrgyzstan",
    "Cambodia",
    "Kiribati",
    "Comoros",
    "South Korea",
    "Kuwait",
    "Cayman Islands",
    "Kazakhstan",
    "Laos",
    "Lebanon",
    "Sri Lanka",
    "Liberia",
    "Lesotho",
    "Libya",
    "Morocco",
    "Moldova",
    "Madagascar",
    "North Macedonia",
    "Myanmar",
    "Mongolia",
    "Macau",
    "Mauritania",
    "Mauritius",
    "Maldives",
    "Malawi",
    "Mexico",
    "Malaysia",
    "Mozambique",
    "Namibia",
    "Nigeria",
    "Nicaragua",
    "Norway",
    "Nepal",
    "New Zealand",
    "Oman",
    "Panama",
    "Peru",
    "Papua New Guinea",
    "Philippines",
    "Pakistan",
    "Poland",
    "Paraguay",
    "Qatar",
    "Romania",
    "Serbia",
    "Russia",
    "Rwanda",
    "Saudi Arabia",
    "Solomon Islands",
    "Seychelles",
    "Sudan",
    "Sweden",
    "Singapore",
    "Saint Helena",
    "Sierra Leone",
    "Somalia",
    "Suriname",
    "South Sudan",
    "São Tomé and Príncipe",
    "Syria",
    "Eswatini",
    "Thailand",
    "Tajikistan",
    "Turkmenistan",
    "Tunisia",
    "Tonga",
    "Turkey",
    "Trinidad and Tobago",
    "Tuvalu",
    "Taiwan",
    "Tanzania",
    "Ukraine",
    "Uganda",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Venezuela",
    "Vietnam",
    "Vanuatu",
    "Samoa",
    "Central African CFA Franc",
    "Organisation of Eastern Caribbean States",
    "International Monetary Fund",
    "West African CFA franc",
    "Collectivités d'Outre-Mer",
    "Yemen",
    "South Africa",
    "Zambia",
    "Zimbabwe"
]
